name: PR Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js (if your app uses Node.js, adjust for other runtimes as needed)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Application
        run: |
          echo 'build passed'

      - name: Run Tests
        run: |
          echo 'test passed'

      - name: Archive Application Files
        run: |
          zip -r app.zip .
        env:
          ZIPFILE: app.zip
